/// <reference types="expo/types" />

// Ambient types for the Expo runtime (e.g. `process.env.EXPO_PUBLIC_*`, the
// typed-routes helpers). Regenerated by `expo` on `expo start` / `expo prebuild`;
// committed here so CI's typecheck has it without needing to run Expo first.
